#!/bin/sh
# See LICENSE file for copyright and license details.

set -e

MEMOFILE=${MEMOFILE:-"$HOME/.memofile"}

die() {
	echo "$1" >&2
	exit 1
}

usage() {
	die 'usage: memo [-nr]'
}

while getopts :nr opt; do
	case "$opt" in
	n)	new='t' ;;
	r)	echo > "$MEMOFILE"; exit ;;
	?)	usage ;;
	esac
done

today=$(date +'%Y-%m-%d')

if [ "$new" ]; then
	read -r text
	if [ -z "$text" ]; then
		die 'Memo is empty. Aborting.'
	else
		printf '%s\t%s\n' "$today" "$text" > "$MEMOFILE"
	fi
else
	date=$(cut -f 1 "$MEMOFILE")
	text=$(cut -f 2 "$MEMOFILE")

	if [ "$date" = "$today" ]; then
		echo "$text"
	else
		die 'Memo file not valid for today.'
	fi
fi
